// status: 'completed' | 'coming_soon' | 'announced' | 'yet_to_announce'
export const DEMO_TRIPS = [
    {
        id: '1',
        destination: 'Banaras Vibes',
        description: 'Experience the spiritual energy of Varanasi with sunrise boat rides, temple visits, and unforgettable Ganga Aarti.',
        startDate: '2026-01-15',
        endDate: '2026-01-18',
        price: 3000,
        totalSlots: 30,
        bookedSlots: 30,
        image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800',
        status: 'completed' as const,
    },
    {
        id: '2',
        destination: 'Manali Adventure',
        description: 'Snow-capped mountains, thrilling activities, and cozy bonfires. Adventure awaits in the Himalayas!',
        startDate: '2026-06-10',
        endDate: '2026-06-15',
        price: 0,
        totalSlots: 35,
        bookedSlots: 0,
        image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800',
        status: 'coming_soon' as const,
    },
    {
        id: '3',
        destination: 'Goa Getaway',
        description: 'Beach parties, water sports, and endless fun under the sun. The ultimate college trip experience!',
        startDate: '2026-08-10',
        endDate: '2026-08-14',
        price: 0,
        totalSlots: 40,
        bookedSlots: 0,
        image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
        status: 'booking_open' as const,
    },
    {
        id: '4',
        destination: 'Rishikesh Rush',
        description: 'White water rafting, camping by the Ganges, and spiritual vibes. The perfect blend of adventure and peace.',
        startDate: '2026-09-05',
        endDate: '2026-09-08',
        price: 0,
        totalSlots: 30,
        bookedSlots: 0,
        image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
        status: 'yet_to_announce' as const,
    },
    {
        id: '5',
        destination: 'Jaipur Royale',
        description: 'Explore the Pink City with palace tours, cultural experiences, and vibrant markets. History meets modernity!',
        startDate: '2026-10-12',
        endDate: '2026-10-15',
        price: 0,
        totalSlots: 25,
        bookedSlots: 0,
        image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800',
        status: 'yet_to_announce' as const,
    },
    {
        id: '6',
        destination: 'Udaipur Dreams',
        description: 'Lake views, royal palaces, and romantic sunsets. Experience the Venice of the East in all its glory.',
        startDate: '2026-11-18',
        endDate: '2026-11-21',
        price: 0,
        totalSlots: 20,
        bookedSlots: 0,
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800',
        status: 'yet_to_announce' as const,
    },
]
